### PR TITLE
add landing message #1

### PR DESCRIPTION
**Pull request by johnwithglassesamustacheandabignose**
..

### CODE REVIEW

**Review by johncosfm — COMMENTED** [review]
youre opinion has been ignored due to it being dumb

**Comment by johnwithglassesamustacheandabignose** [comment]
> 

cant care

**Comment by johncosfm** [comment]
ok

**Review by johncosfm — CHANGES_REQUESTED** [review]
ok

**Review by johncosfm — APPROVED** [review]
i have tears in my eyes youre a visionary at work

**Pull request merged**
